// Code generated by go generate. DO NOT EDIT.

// Generated from Debian project md/netbase at https://salsa.debian.org
// At 2021-09-16T08:40:30Z
// File etc/protocols
// Commit 51aec3f4bf47ca303c46287dd27f0c952d8030c7

package netdb

var BuiltinProtocols []Protocol = builtinProtocols
var builtinProtocols = []Protocol{
		{ Name: "ip", Number: 0, Aliases: []string{"IP",} },
		{ Name: "hopopt", Number: 0, Aliases: []string{"HOPOPT",} },
		{ Name: "icmp", Number: 1, Aliases: []string{"ICMP",} },
		{ Name: "igmp", Number: 2, Aliases: []string{"IGMP",} },
		{ Name: "ggp", Number: 3, Aliases: []string{"GGP",} },
		{ Name: "ipencap", Number: 4, Aliases: []string{"IP-ENCAP",} },
		{ Name: "st", Number: 5, Aliases: []string{"ST",} },
		{ Name: "tcp", Number: 6, Aliases: []string{"TCP",} },
		{ Name: "egp", Number: 8, Aliases: []string{"EGP",} },
		{ Name: "igp", Number: 9, Aliases: []string{"IGP",} },
		{ Name: "pup", Number: 12, Aliases: []string{"PUP",} },
		{ Name: "udp", Number: 17, Aliases: []string{"UDP",} },
		{ Name: "hmp", Number: 20, Aliases: []string{"HMP",} },
		{ Name: "xns-idp", Number: 22, Aliases: []string{"XNS-IDP",} },
		{ Name: "rdp", Number: 27, Aliases: []string{"RDP",} },
		{ Name: "iso-tp4", Number: 29, Aliases: []string{"ISO-TP4",} },
		{ Name: "dccp", Number: 33, Aliases: []string{"DCCP",} },
		{ Name: "xtp", Number: 36, Aliases: []string{"XTP",} },
		{ Name: "ddp", Number: 37, Aliases: []string{"DDP",} },
		{ Name: "idpr-cmtp", Number: 38, Aliases: []string{"IDPR-CMTP",} },
		{ Name: "ipv6", Number: 41, Aliases: []string{"IPv6",} },
		{ Name: "ipv6-route", Number: 43, Aliases: []string{"IPv6-Route",} },
		{ Name: "ipv6-frag", Number: 44, Aliases: []string{"IPv6-Frag",} },
		{ Name: "idrp", Number: 45, Aliases: []string{"IDRP",} },
		{ Name: "rsvp", Number: 46, Aliases: []string{"RSVP",} },
		{ Name: "gre", Number: 47, Aliases: []string{"GRE",} },
		{ Name: "esp", Number: 50, Aliases: []string{"IPSEC-ESP",} },
		{ Name: "ah", Number: 51, Aliases: []string{"IPSEC-AH",} },
		{ Name: "skip", Number: 57, Aliases: []string{"SKIP",} },
		{ Name: "ipv6-icmp", Number: 58, Aliases: []string{"IPv6-ICMP",} },
		{ Name: "ipv6-nonxt", Number: 59, Aliases: []string{"IPv6-NoNxt",} },
		{ Name: "ipv6-opts", Number: 60, Aliases: []string{"IPv6-Opts",} },
		{ Name: "rspf", Number: 73, Aliases: []string{"RSPF","CPHB",} },
		{ Name: "vmtp", Number: 81, Aliases: []string{"VMTP",} },
		{ Name: "eigrp", Number: 88, Aliases: []string{"EIGRP",} },
		{ Name: "ospf", Number: 89, Aliases: []string{"OSPFIGP",} },
		{ Name: "ax.25", Number: 93, Aliases: []string{"AX.25",} },
		{ Name: "ipip", Number: 94, Aliases: []string{"IPIP",} },
		{ Name: "etherip", Number: 97, Aliases: []string{"ETHERIP",} },
		{ Name: "encap", Number: 98, Aliases: []string{"ENCAP",} },
		{ Name: "pim", Number: 103, Aliases: []string{"PIM",} },
		{ Name: "ipcomp", Number: 108, Aliases: []string{"IPCOMP",} },
		{ Name: "vrrp", Number: 112, Aliases: []string{"VRRP",} },
		{ Name: "l2tp", Number: 115, Aliases: []string{"L2TP",} },
		{ Name: "isis", Number: 124, Aliases: []string{"ISIS",} },
		{ Name: "sctp", Number: 132, Aliases: []string{"SCTP",} },
		{ Name: "fc", Number: 133, Aliases: []string{"FC",} },
		{ Name: "mobility-header", Number: 135, Aliases: []string{"Mobility-Header",} },
		{ Name: "udplite", Number: 136, Aliases: []string{"UDPLite",} },
		{ Name: "mpls-in-ip", Number: 137, Aliases: []string{"MPLS-in-IP",} },
		{ Name: "manet", Number: 138, Aliases: []string{} },
		{ Name: "hip", Number: 139, Aliases: []string{"HIP",} },
		{ Name: "shim6", Number: 140, Aliases: []string{"Shim6",} },
		{ Name: "wesp", Number: 141, Aliases: []string{"WESP",} },
		{ Name: "rohc", Number: 142, Aliases: []string{"ROHC",} },
	}
	